version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: DistribuidoraAriel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guido2907
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: gunicorn distribuidora.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DATABASE_URL=postgres://postgres:guido2907@db:5432/DistribuidoraAriel
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
