# Generated by Django 4.2.21 on 2025-05-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_bulto',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
