# Generated by Django 4.2.21 on 2025-05-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_precio_producto_precio_bulto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_por_bulto',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
