# Generated by Django 4.2.21 on 2025-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_producto_cantidad_por_bulto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('attempts', models.IntegerField(default=0)),
                ('permanently_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
